"""empty message

Revision ID: 01d47f4fdc87
Revises: 8a6f6a9be023
Create Date: 2023-06-26 18:56:24.597804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d47f4fdc87'
down_revision = '8a6f6a9be023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('billing_address')

    # ### end Alembic commands ###
