"""empty message

Revision ID: 04d039cfaa18
Revises: 3f5448829ec0
Create Date: 2023-06-09 18:12:13.880089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d039cfaa18'
down_revision = '3f5448829ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_category',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_category',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
