"""empty message

Revision ID: 0650d36514a2
Revises: 1691145907b6
Create Date: 2023-06-21 17:25:27.747167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0650d36514a2'
down_revision = '1691145907b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number_hash', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('cvc_hash', sa.Text(), nullable=False))
        batch_op.drop_constraint('payment_method_card_number_key', type_='unique')
        batch_op.create_unique_constraint(None, ['card_number_hash'])
        batch_op.drop_column('card_number')
        batch_op.drop_column('cvc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvc', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_number', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('payment_method_card_number_key', ['card_number'])
        batch_op.drop_column('cvc_hash')
        batch_op.drop_column('card_number_hash')

    # ### end Alembic commands ###
