"""empty message

Revision ID: 182436221bb3
Revises: c185608c80d4
Create Date: 2023-06-14 18:47:52.004370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182436221bb3'
down_revision = 'c185608c80d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('card_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('cvc',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_format_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'book_format', ['book_format_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit')
        batch_op.drop_column('book_format_id')

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.alter_column('cvc',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('card_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('card_number',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    op.drop_table('history')
    # ### end Alembic commands ###
