"""empty message

Revision ID: 3689406aafad
Revises: 
Create Date: 2023-07-10 17:29:23.935408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3689406aafad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_payment_method_id_fkey', type_='foreignkey')
        batch_op.drop_column('payment_method_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transaction_payment_method_id_fkey', 'payment_method', ['payment_method_id'], ['id'])

    # ### end Alembic commands ###
