"""empty message

Revision ID: 427722b1747b
Revises: 182436221bb3
Create Date: 2023-06-15 14:32:10.756271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427722b1747b'
down_revision = '182436221bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_constraint('support_transaction_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('support_book_id_fkey', type_='foreignkey')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('book_id')
        batch_op.drop_column('enquiries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enquiries', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('support_book_id_fkey', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('support_transaction_id_fkey', 'transaction', ['transaction_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
