"""empty message

Revision ID: 489d33b2edad
Revises: 536082484ec4
Create Date: 2023-06-16 19:08:44.713789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d33b2edad'
down_revision = '536082484ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('payment_methods')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('card_type')

    # ### end Alembic commands ###
