"""empty message

Revision ID: 680e3eb863fb
Revises: df581ff65765
Create Date: 2023-06-06 17:09:06.308271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680e3eb863fb'
down_revision = 'df581ff65765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('average_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
