"""empty message

Revision ID: 9ff82818ed85
Revises: 4b9d1b4585e0
Create Date: 2023-06-28 21:39:51.595252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff82818ed85'
down_revision = '4b9d1b4585e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.drop_column('support_created')

    # ### end Alembic commands ###
